[cluster_info]
cores_per_node: cluster_info cores_per_node

[joblist]
interactive: False
inputs: job, jobs_from, args, nexpected_per_job=0, nexpected_per_process=0
command: run_parallel_generic_job {job} --jobs_from {jobs_from} {args} --jobname {jobtag} --keep_directories
restart: check_jobs --restart --expected_per_job {nexpected_per_job} --expected_per_process {nexpected_per_process}
progress: jobs_in_queue {jobtag}
checks: check_jobs --expected_per_job {nexpected_per_job} --expected_per_process {nexpected_per_process}

[interactive]
interactive: True
inputs: command, args
command: {command} {args}

[generic] 
interactive: False 
inputs: job, nmin, nmax, args, nexpected_per_job=0, nexpected_per_process=0 
command: run_parallel_generic_job {job} {nmin} {nmax} {args} --jobname {jobtag} --keep_directories 
restart: check_jobs --restart --expected_per_job {nexpected_per_job} --expected_per_process {nexpected_per_process} 
progress: jobs_in_queue {jobtag} 
checks: check_jobs --expected_per_job {nexpected_per_job} --expected_per_process {nexpected_per_process}
